### ISSUE TITLE
Kotlin Multiplatform?

### ISSUE THREAD

**Issue by manosbatsis** [sigbla/sigbla-app#67]
How easy would be to migrate this project to multi-platform support?

**Comment by cfelde** [comment]
It's a good suggestion and something I have in mind, but not something I'm focusing on at the moment.

It's probably a 2.x type feature, with current focus on better test coverage, stabilize core APIs, and add more auxiliary functionality like database/xslt/csv import/export, more chart types, potentially something for kotlin dataframe, better support for statistics and other such core functions.

I will continue to keep it in mind for when the time is right, thanks for asking.
